# name: gitCI

# on:
#   push:
#     branches: 
#       - main

# permissions:
#   contents: read
#   id-token: write

# jobs:
#   job1:
#     runs-on: self-hosted
#     steps:
#       - name: My first job
#         run: echo "my first job"


#   job2:
#     runs-on: self-hosted
#     steps :
#        - name: Install Terraform
      
#          uses: little-core-labs/install-terraform@v2.0.0
   
          
#   job3:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Azure Login
#         uses: Azure/login@v2.3.0
#         with:
#           client-id: 1bdbdf86-da16-49a0-a2d4-91a18fe17779
#           tenant-id: df7d1ae3-5176-4f7e-914b-b0fbb8b85c9f
#           subscription-id: 74282b2c-f351-49d2-8fc1-345ec077bafb

#   job4:
#     runs-on: self-hosted
#     needs: job3
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.6.3

#       - name: Terraform Init
#         run: terraform init
#         working-directory: .

#       - name: Terraform Plan
#         run: terraform plan
#         working-directory: .

#   # job5:
#   #   runs-on: ubuntu-latest
#   #   needs: job4
#   #   steps:
#   #     - name: Approve Workflow [Manual]
#   #       run: echo Approve Workflow [Manual]


name: Terraform-Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure Login
        run: az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3

      - name: Terraform Init
        run: terraform init
        working-directory: ./githubactionpractice

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./githubactionpractice

